// Regenerates the bundled geometry. Run with `npm run data`.
// Sources are deliberately permissive so the output can ship inside the package:
//   • Natural Earth (via world-atlas): public domain
//   • Datameet india-composite: CC-0
// The two are merged into one dataset; see scripts/india-boundary.mjs.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { feature } from "topojson-client";
import { applyOfficialIndia } from "./india-boundary.mjs";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "data");
const WORLD_URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";
const INDIA_URL = "https://cdn.jsdelivr.net/gh/datameet/maps@master/Country/india-composite.geojson";
const ISO_URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson";

/** Numeric id → ISO alpha-2, so `countryColors` can be keyed by country code. */
async function fetchIsoCodes() {
  try {
    const fc = await fetch(ISO_URL).then((r) => r.json());
    const map = new Map();
    for (const f of fc.features) {
      const p = f.properties || {};
      const num = String(p.ISO_N3 ?? p.iso_n3 ?? "").replace(/^0+/, "");
      const a2 = p.ISO_A2_EH || p.ISO_A2 || p.iso_a2;
      if (num && a2 && a2 !== "-99") map.set(num, a2);
    }
    console.log(`  ${map.size} ISO codes`);
    return map;
  } catch (e) {
    console.warn(`  ISO lookup unavailable (${e.message}); continuing without codes`);
    return new Map();
  }
}

/** Distance-based decimation: cheap, stable, and good enough at screen scale. */
function simplifyRing(ring, tol) {
  const out = [ring[0]];
  for (const p of ring) {
    const last = out[out.length - 1];
    if (Math.abs(p[0] - last[0]) + Math.abs(p[1] - last[1]) > tol) out.push(p);
  }
  out.push(ring[0]);
  return out;
}

function bboxSpan(ring) {
  let minX = 180, maxX = -180, minY = 90, maxY = -90;
  for (const [x, y] of ring) {
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  return Math.max(maxX - minX, maxY - minY);
}

function simplifyGeometry(geom, { tol, minSpan, round }) {
  const polys = geom.type === "Polygon" ? [geom.coordinates] : geom.coordinates;
  const kept = [];
  for (const poly of polys) {
    const rings = [];
    for (const ring of poly) {
      if (bboxSpan(ring) < minSpan) continue;
      const simple = simplifyRing(ring, tol);
      if (simple.length < 5) continue;
      rings.push(simple.map(([x, y]) => [+x.toFixed(round), +y.toFixed(round)]));
    }
    if (rings.length) kept.push(rings);
  }
  return kept.length ? { type: "MultiPolygon", coordinates: kept } : null;
}

const countPoints = (geom) =>
  geom.coordinates.reduce((a, poly) => a + poly.reduce((b, r) => b + r.length, 0), 0);

async function main() {
  mkdirSync(OUT, { recursive: true });

  console.log("→ world-atlas 110m");
  const topo = await fetch(WORLD_URL).then((r) => r.json());
  const iso = await fetchIsoCodes();
  const countries = feature(topo, topo.objects.countries).features;
  const shapes = [];
  for (const f of countries) {
    const g = simplifyGeometry(f.geometry, { tol: 0.14, minSpan: 0.45, round: 2 });
    if (!g) continue;
    const shape = { id: f.id, name: f.properties?.name, geometry: g };
    const code = iso.get(String(f.id).replace(/^0+/, ""));
    if (code) shape.iso = code;
    shapes.push(shape);
  }
  const missing = shapes.filter((s) => !s.iso).length;
  if (missing) console.log(`  ${missing} countries without an ISO code`);

  console.log("→ india-composite (Survey of India boundary)");
  const raw = await fetch(INDIA_URL).then((r) => r.json());
  const f = raw.type === "FeatureCollection" ? raw.features[0] : raw;
  // Finer than the 0.14 used for the rest of the world because India's outline is the
  // one people zoom into, but not so fine that it dwarfs its neighbours in the
  // same dataset, which it would at the source resolution.
  const india = simplifyGeometry(f.geometry || f, { tol: 0.06, minSpan: 0.08, round: 2 });
  const { shapes: merged, trimmed } = applyOfficialIndia(shapes, india);
  console.log(`  subtracted from ${trimmed.length}: ${trimmed.join(", ")}`);

  const worldPoints = merged.reduce((a, s) => a + countPoints(s.geometry), 0);
  const worldJson = JSON.stringify(merged);
  writeFileSync(
    join(OUT, "world.js"),
    `/* @ts-self-types="../../types/data/world.d.ts" */\n\n` +
      `// Generated by scripts/generate-data.mjs. Do not edit.\n` +
      `// Sources: Natural Earth 1:110m via world-atlas (public domain) and\n` +
      `// Datameet india-composite (CC-0) for India, per the Survey of India\n` +
      `// boundary. Overlaps between the two are resolved in favour of India.\n` +
      `export const world = ${worldJson};\nexport default world;\n`,
  );
  console.log(`  ${merged.length} countries · ${worldPoints} points · ${Math.round(worldJson.length / 1024)} KB`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
