// Regenerates the bundled place table. Run with `npm run places`.
// Source: Natural Earth 10m populated places (public domain, no attribution
// required)  -  deliberately chosen over GeoNames, which is CC BY 4.0 and would
// put an attribution obligation on everyone shipping this package.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "data");
const URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_populated_places_simple.geojson";

/** Everything above this rank ships regardless of how small it is. */
const OTHERS = 4200;

/** The packed format uses these, so they cannot survive inside a name. */
const clean = (s) => String(s || "").replace(/[;|]/g, " ").trim();

const run = async () => {
  console.log("fetching Natural Earth populated places…");
  const fc = await fetch(URL).then((r) => {
    if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
    return r.json();
  });

  const seen = new Set();
  const rows = [];
  for (const f of fc.features) {
    const p = f.properties || {};
    const name = clean(p.name || p.nameascii);
    if (!name) continue;
    const [lon, lat] = f.geometry?.coordinates || [p.longitude, p.latitude];
    if (!Number.isFinite(lon) || !Number.isFinite(lat)) continue;
    const cc = clean(p.iso_a2 || p.adm0_a3 || "").slice(0, 2).toUpperCase();
    const pop = Number(p.pop_max || p.pop_min || 0);
    // Only worth the bytes when it actually disambiguates.
    const region = clean(p.adm1name);
    const adm1 = region && region.toLowerCase() !== name.toLowerCase() ? region : "";

    // Natural Earth carries a few duplicates at the same point. Two different
    // Springfields in two different states are not duplicates, so the region
    // has to be part of the key.
    const key = `${name.toLowerCase()}|${cc}|${adm1.toLowerCase()}`;
    if (seen.has(key)) continue;
    seen.add(key);

    rows.push({
      name,
      lon: Math.round(lon * 100),
      lat: Math.round(lat * 100),
      cc,
      // Thousands: plenty for ranking, and one to three digits instead of seven.
      pop: Math.round(pop / 1000),
      adm1,
      // Several national capitals carry no population in Natural Earth, so
      // a pure population cut would silently drop them.
      capital: /capital/i.test(String(p.featurecla || "")),
    });
  }

  // Biggest first, so a prefix scan can stop early and still rank well.
  rows.sort((a, b) => b.pop - a.pop);

  const capitals = rows.filter((r) => r.capital);
  const others = rows.filter((r) => !r.capital).slice(0, OTHERS);
  const kept = [...capitals, ...others].sort((a, b) => b.pop - a.pop);

  // The region is only worth its bytes where the name repeats inside a country.
  const tally = new Map();
  for (const r of kept) {
    const k = `${r.name.toLowerCase()}|${r.cc}`;
    tally.set(k, (tally.get(k) || 0) + 1);
  }
  let disambiguated = 0;
  for (const r of kept) {
    if (tally.get(`${r.name.toLowerCase()}|${r.cc}`) > 1 && r.adm1) disambiguated++;
    else r.adm1 = "";
  }

  const table = kept.map((r) => `${r.name}|${r.lon}|${r.lat}|${r.cc}|${r.pop}|${r.adm1}`).join(";");
  const body =
    `// Generated by scripts/generate-places.mjs. Do not edit.\n` +
    `// Source: Natural Earth 10m populated places (public domain).\n` +
    `// "name|lon|lat|cc|pop|region", coordinates in hundredths of a degree,\n` +
    `// population in thousands, region blank when it adds nothing.\n` +
    `export const placeTable = ${JSON.stringify(table)};\n`;

  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, "places.js"), body);
  const gz = (gzipSync(Buffer.from(body)).length / 1024).toFixed(1);
  console.log(
    `  ${kept.length} places (${capitals.length} capitals, ${disambiguated} need a region) · ` +
    `${(body.length / 1024).toFixed(0)} KB raw · ${gz} KB gz`
  );
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
